league_history/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns=patterns('lol.views',
	url(r'^game/(?P<region>NA|EUW|EUNE)/(?P<game_id>\d{1,12})/$', 'view_game', name='view_game'),
	url(r'^game/$', 'game_list', name='game_list'),
	url(r'^summoner/(?P<region>NA|EUW|EUNE)/(?P<account_id>\d{1,12})/(?P<slug>[-\w]*?)/games/', 'view_summoner_games', name='view_summoner_games'),
	url(r'^summoner/(?P<region>NA|EUW|EUNE)/(?P<account_id>\d{1,12})/(?P<slug>[-\w]*?)/champions/(?P<champion_id>\d{1,12})/(?P<champion_slug>[-\w])*/', 'view_summoner_specific_champion', name='view_summoner_specific_champion'),
	url(r'^summoner/(?P<region>NA|EUW|EUNE)/(?P<account_id>\d{1,12})/(?P<slug>[-\w]*?)/champions/', 'view_summoner_champions', name='view_summoner_champions'),
	url(r'^summoner/(?P<region>NA|EUW|EUNE)/(?P<account_id>\d{1,12})/(?P<slug>[-\w]*?)/inventory/', 'view_summoner_inventory', name='view_summoner_inventory'),
	url(r'^summoner/(?P<region>NA|EUW|EUNE)/(?P<account_id>\d{1,12})/(?P<slug>[-\w]*?)/', 'view_summoner', name='view_summoner'),
	url(r'^summoner/(?P<region>NA|EUW|EUNE)/(?P<account_id>\d{1,12})/', 'view_summoner_redirect', name='view_summoner_redirect'),
	url(r'^champions/(?P<champion_id>\d{1,12})/(?P<champion_slug>[-\w]*?)/items/$', 'view_champion_items', name='view_champion_items'),
	url(r'^champions/(?P<champion_id>\d{1,12})/(?P<champion_slug>[-\w]*?)/$', 'view_champion', name='view_champion'),
	url(r'^champions/$', 'view_all_champions', name='view_all_champions'),
	url(r'^search/([-\w\s]*)/$', 'search', name='search'),
	url(r'^run_auto/$', 'run_auto'),

	url(r'^admin/status/', 'client_status'),
	url(r'^admin/test_items/', 'test_items'),

	# Uncomment the admin/doc line below to enable admin documentation:
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
)
urlpatterns+=patterns('lol.ajax',
	url(r'^ajax/player_info/(\d{1,12})/$', 'player_info', name='ajax_player_info'),
	url(r'^ajax/summoner_games/(?P<region>0|1|2)/(?P<account_id>\d{1,12})/$', 'summoner_games', name='ajax_summoner_games'),
	url(r'^ajax/force_update/(?P<region>0|1|2)/(?P<account_id>\d{1,12})/$', 'force_update', name='ajax_force_update'),
	url(r'^ajax/force_update_status/(?P<region>0|1|2)/(?P<account_id>\d{1,12})/$', 'force_update_status', name='ajax_force_update_status'),
)
# urlpatterns+=patterns('', url(r'^redis/status/', include('redis_cache.stats.urls', namespace='redis_cache')))

lol/models.py
from datetime import datetime, timedelta
from django.db import models, transaction
from django.utils.text import slugify
from lol.core.game_types import GAME_TYPES, RANKED_SOLO_QUEUE_TYPES, RANKED_GAME_TYPES
from lol.core.servers import prepare_servers, REGIONS
from lol.utils import log_event, get_cached_value, set_cached_value
from pytz import timezone
from time import sleep
import requests
import json

MODES=(
	(0, 'Custom'), (1, 'Bot'), (2, 'Normal'), (3, 'Solo'), (4, 'Premade'), (5, 'Team'), (6, 'Aram'), (7, 'One For All'), (8, 'Showdown'),
	(9, 'Hexakill'), (10, 'URF'), (11, 'Nightmare Bot'), (12, 'Ascension'), (13, 'King Poro'), (99, '?')
)
MAPS=((0, 'Old Twisted Treeline'), (1, 'Summoners Rift'), (2, 'Dominion'), (3, 'Howling Abyss'), (4, 'Twisted Treeline'), (5, 'New Summoners Rift'), (9, '?'))
# {'queue', 'mode', 'map'}
TIERS=((1, 'BRONZE'), (2, 'SILVER'), (3, 'GOLD'), (4, 'PLATINUM'), (5, 'DIAMOND'), (6, 'CHALLENGER'))
DIVISIONS=((1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'))

prepare_servers()


class Summoner(models.Model):
	region=models.IntegerField(choices=REGIONS, default=0)
	account_id=models.IntegerField(db_index=True)
	summoner_id=models.IntegerField()
	name=models.CharField(max_length=64)
	internal_name=models.CharField(max_length=64)
	level=models.IntegerField()
	profile_icon=models.IntegerField()
	runes=models.TextField(default='{}', blank=True)
	masteries=models.TextField(default='{}', blank=True)
	update_automatically=models.BooleanField(db_index=True, default=False)
	fully_update=models.BooleanField(default=False)
	time_created=models.DateTimeField(auto_now_add=True)
	time_updated=models.DateTimeField(default=datetime.now(timezone('UTC')))
	# time_extra_updated=models.DateTimeField(auto_now_add=True)

	@models.permalink
	def get_absolute_url(self):
		return ('view_summoner', (), {
			'region':self.get_region_display(),
			'account_id':self.account_id,
			'slug':self.slug
		})

	@models.permalink
	def get_games_url(self):
		return ('view_summoner_games', (), {
			'region':self.get_region_display(),
			'account_id':self.account_id,
			'slug':self.slug
		})

	@models.permalink
	def get_champions_url(self):
		return ('view_summoner_champions', (), {
			'region':self.get_region_display(),
			'account_id':self.account_id,
			'slug':self.slug
		})

	def get_runes(self):
		return json.loads(self.runes)

	def get_masteries(self):
		return json.loads(self.masteries)

	def get_rating(self):
		try:
			rating=SummonerRating.objects.get(summoner=self, game_map=1, game_mode=3)
		except SummonerRating.DoesNotExist:
			rating=SummonerRating(summoner=self, game_map=1, game_mode=3, wins=0, losses=0)
			rating.save()
		return rating

	@property
	def needs_update(self):
		if self.time_updated<(datetime.now(timezone('UTC')) - timedelta(hours=1)):
			updating=get_cached_value('summoner/{}/{}/updating'.format(self.region, self.account_id))
			if updating is not None:
				return updating
			else:
				return True
		else:
			return False

	@property
	def slug(self):
		return slugify(self.name) if len(slugify(self.name))>0 else '-'

	def __unicode__(self):
		return self.name

	class Meta:
		index_together=[
			("region", "account_id"),
		]
		unique_together=(("region", "account_id"))


class SummonerRankedStatistics(models.Model):
	summoner=models.ForeignKey(Summoner, db_index=True)
	season=models.IntegerField()
	champion_id=models.IntegerField()
	wins=models.IntegerField()
	losses=models.IntegerField()
	kills=models.IntegerField()
	deaths=models.IntegerField()
	assists=models.IntegerField()
	minion_kills=models.IntegerField()
	gold=models.IntegerField()
	turrets_destroyed=models.IntegerField()
	damage_dealt=models.IntegerField()
	physical_damage_dealt=models.IntegerField()
	magical_damage_dealt=models.IntegerField()
	damage_taken=models.IntegerField()
	double_kills=models.IntegerField()
	triple_kills=models.IntegerField()
	quadra_kills=models.IntegerField()
	penta_kills=models.IntegerField()
	time_spent_dead=models.IntegerField()
	maximum_kills=models.IntegerField()
	maximum_deaths=models.IntegerField()


class SummonerRating(models.Model):
	summoner=models.ForeignKey(Summoner, db_index=True)
	game_map=models.IntegerField(choices=MAPS, db_index=True, null=False)
	game_mode=models.IntegerField(choices=MODES, db_index=True, null=False)
	wins=models.IntegerField()
	losses=models.IntegerField()
	league=models.CharField(max_length=127, null=True, blank=True)
	tier=models.IntegerField(choices=TIERS, null=True, blank=True)
	division=models.IntegerField(choices=DIVISIONS, null=True, blank=True)
	rank=models.IntegerField(null=True, blank=True)
	miniseries_target=models.IntegerField(default=0)
	miniseries_wins=models.IntegerField(default=0)
	miniseries_losses=models.IntegerField(default=0)

	@property
	def rank_to_number(self):
		return rank_to_number(self.tier, self.division, self.rank)

	class Meta:
		index_together=[
			("summoner", "game_map", "game_mode")
		]
		unique_together=(("summoner", "game_map", "game_mode"))


class Game(models.Model):
	region=models.IntegerField(choices=REGIONS, default=0)
	game_id=models.IntegerField()
	game_map=models.IntegerField(choices=MAPS, db_index=True)
	game_mode=models.IntegerField(choices=MODES, db_index=True)
	time=models.DateTimeField(db_index=True)
	blue_team_won=models.BooleanField()
	invalid=models.BooleanField(default=False)
	unfetched_players=models.CharField(max_length=256, blank=True)
	fetched=models.BooleanField(default=False)

	@models.permalink
	def get_absolute_url(self):
		return ('view_game', (), {
			'region':self.get_region_display(),
			'game_id':self.game_id,
		})

	def __unicode__(self):
		return unicode(self.time.isoformat())

	class Meta:
		ordering=['-time',]
		index_together=[
			("game_map", "game_mode"),
			("game_id", "region")
		]
		unique_together=(("region", "game_id"))


class Player(models.Model):
	game=models.ForeignKey(Game, db_index=True)
	summoner=models.ForeignKey('Summoner', db_index=True)

	won=models.BooleanField()

	tier=models.IntegerField(choices=TIERS, null=True, blank=True)
	division=models.IntegerField(choices=DIVISIONS, null=True, blank=True)
	rank=models.IntegerField(null=True, blank=True)

	afk=models.BooleanField()
	leaver=models.BooleanField()

	blue_team=models.BooleanField()

	ping=models.IntegerField()
	queue_length=models.IntegerField()
	premade_size=models.IntegerField()

	experience_earned=models.IntegerField()
	boosted_experience_earned=models.IntegerField()

	ip_earned=models.IntegerField()
	boosted_ip_earned=models.IntegerField()

	summoner_level=models.IntegerField()

	summoner_spell1=models.IntegerField()
	summoner_spell2=models.IntegerField()

	champion_id=models.IntegerField()
	skin_index=models.IntegerField()
	skin_name=models.CharField(max_length=64, null=True, blank=True)

	champion_level=models.IntegerField()

	items=models.CharField(max_length=43)

	kills=models.IntegerField()
	deaths=models.IntegerField()
	assists=models.IntegerField()

	minion_kills=models.IntegerField()

	neutral_minions_killed=models.IntegerField()
	neutral_minions_killed_your_jungle=models.IntegerField()
	neutral_minions_killed_enemy_jungle=models.IntegerField()

	gold=models.IntegerField()

	physical_damage_dealt=models.IntegerField()
	magic_damage_dealt=models.IntegerField()
	true_damage_dealt=models.IntegerField()
	damage_dealt=models.IntegerField()

	physical_damage_taken=models.IntegerField()
	magic_damage_taken=models.IntegerField()
	true_damage_taken=models.IntegerField()
	damage_taken=models.IntegerField()

	total_time_crowd_control_dealt=models.IntegerField()
	total_healing_done=models.IntegerField()
	time_spent_dead=models.IntegerField()

	largest_multikill=models.IntegerField()
	largest_killing_spree=models.IntegerField()
	largest_critical_strike=models.IntegerField()

	turrets_destroyed=models.IntegerField()
	inhibitors_destroyed=models.IntegerField()

	sight_wards_bought_in_game=models.IntegerField()
	vision_wards_bought_in_game=models.IntegerField()
	ward_placed=models.IntegerField()
	ward_killed=models.IntegerField()

	node_neutralize=models.IntegerField(null=True, blank=True)
	node_neutralize_assist=models.IntegerField(null=True, blank=True)
	node_capture=models.IntegerField(null=True, blank=True)
	node_capture_assist=models.IntegerField(null=True, blank=True)
	victory_point_total=models.IntegerField(null=True, blank=True)
	team_objective=models.IntegerField(null=True, blank=True)
	total_player_score=models.IntegerField(null=True, blank=True)
	objective_player_score=models.IntegerField(null=True, blank=True)
	combat_player_score=models.IntegerField(null=True, blank=True)
	total_score_rank=models.IntegerField(null=True, blank=True)

	@property
	def get_items(self):
		return self.items.split('|')[1:-1][:6]

	@property
	def length(self):
		ip=self.ip_earned - self.boosted_ip_earned if self.ip_earned - self.boosted_ip_earned<=145 else (self.ip_earned - self.boosted_ip_earned) - 150
		if self.game.game_mode not in (2, 3, 4, 5):
			return 0
		if self.game.game_map in (1, 4, 5):  # classic, twisted treeline
			base=18 if self.won else 16
			mingain=2.26975458333333 if self.won else 1.38803291666667
			max_length=55
			if (self.won and ip==76) or (not self.won and ip==51):
				result=25
			elif (self.won and ip>=145) or (not self.won and ip>=94):
				result=55
			else:
				# result=round((ip-base)/mingain, 1)
				result=(ip - base) / mingain
		elif self.game.game_map==2:  # dominion
			base=20 if self.won else 12
			mingain=2 if self.won else 1
			max_length=55
			result=(ip - base) / mingain
		return result if result<=max_length else max_length

	@property
	def gpm(self):
		if self.length>0:
			return round(self.gold / self.length)
		else:
			return 0

	@property
	def rank_to_number(self):
		return rank_to_number(self.tier, self.division, self.rank) if self.tier is not None else 0

	@models.permalink
	def get_absolute_url(self):
		return ('view_game', (), {
			'region':self.game.get_region_display(),

lol/forms.py
from django import forms
from lol.models import MAPS, MODES


class MapModeForm(forms.Form):
	def __init__(self, *args, **kwargs):
		super(MapModeForm, self).__init__(*args, **kwargs)
		self.elo_filter=kwargs.get('elo_filter', 0)
	maps=[(-1, 'All maps'),]
	maps.extend(MAPS)
	modes=[(-1, 'All modes'),]
	modes.extend(MODES)
	game_map=forms.ChoiceField(required=False, choices=maps[:-1], widget=forms.Select(attrs={'class':'form-control input-sm'}))
	game_mode=forms.ChoiceField(required=False, choices=modes[:-1], widget=forms.Select(attrs={'class':'form-control input-sm'}))
	elo_filter=forms.ChoiceField(required=False, choices=((-1, 'All'), (0, 'Bronze league'), (1, 'Silver league'), (2, 'Gold league'), (3, 'Platinum league')), widget=forms.Select(attrs={'class':'col-md-2'}))

lol/templates/run_auto.html.j2
{% extends 'base.html.j2' %}

{% block content %}
			{% for summoner in summoners %}<a href='{{summoner.get_absolute_url()}}'>{{summoner}}</a><br>{% endfor %}
{%- endblock %}

lol/templates/view_game.jinja
{% extends 'base.jinja' %}

{% block extra_css %}
		<link href="{{STATIC_URL}}css/morris.css" rel="stylesheet" type="text/css">
{%- endblock %}

{% block post_scripts %}
		{%- if debug %}
		<script src='{{STATIC_URL}}debug/items.js' type='text/javascript'></script>
		<script src='{{STATIC_URL}}debug/core.js' type='text/javascript'></script>
		<script src='{{STATIC_URL}}debug/game.js' type='text/javascript'></script>
		<script src='{{STATIC_URL}}debug/graph.js' type='text/javascript'></script>
		{%- else %}
		<script src="{{STATIC_URL}}js/main.js" type="text/javascript"></script>
		{%- endif %}
		<script src='{{STATIC_URL}}js/morris.js' type='text/javascript'></script>
		<script type="text/javascript">
			var game_pk={{game.pk}};
			var game_region={{game.region}};
			var chart=[{'chart_options':{'type':'Donut', 'element':'damage-dealt-graph', 'useImages':true}, 'data_options':{'y':'damage_dealt'}}, {'chart_options':{'type':'Donut', 'element':'damage-taken-graph', 'useImages':true}, 'data_options':{'y':'damage_taken'}}, {'chart_options':{'type':'Donut', 'element':'gpm-graph', 'useImages':true}, 'data_options':{'y':'gpm'}}, {'chart_options':{'type':'Donut', 'element':'gold-graph', 'useImages':true}, 'data_options':{'y':'gold'}}];
			var chart_data={{chart_data|safe}};
		</script>
{%- endblock %}

{% block content %}
			<div class='row'>
				<div class='col-md-12 summoner-header' style='background-image:url({{STATIC_URL}}img/map-backgrounds/{{game.game_map}}.png)'>
					<div class='info-block pull-right'>
						{%- if metadata.avg_elo %}
						<div>
							<b>{{metadata.avg_elo|number_to_rank|display_rank}}</b>
							<small>AVG LEAGUE</small>
						</div>
						{% endif -%}
						<div>
							<b>{{metadata.mode}}</b>
							<small>MODE</small>
						</div>
						<div>
							<b>{{metadata.map|upper}}</b>
							<small>MAP</small>
						</div>
						<div>
							<b>{{game.time|date('N d')|upper}}</b>
							<small>{{game.time|naturaltime|upper}}</small>
						</div>
					</div>
					<div class='bottom-right large'>
						<span class='green'>{{metadata.stats.winner.kills}}</span>/<span class='red'>{{metadata.stats.loser.kills}}</span>
					</div>
				</div>
				<div class='col-md-12'>{% if not update_in_queue %}
					<table class='game-list table table-condensed'>
						<thead>
							<tr>
								<th style='width:45px;'></th>
								<th style='width:100px;'>Summoner</th>
								<th style='width:50px'>K/D/A</th>
								<th style='width:50px'>Gold</th>
								<th style='width:50px'>CS</th>
								<th style='width:50px'>Dealt</th>
								<th style='width:50px'>Taken</th>
								<th style='width:85px;'>Spells</th>
								<th style='width:215px;'>Items</th>
								<th style='width:150px;'></th>
							</tr>
						</thead>
						{%- for team in players|groupby('won')|reverse %}
						{%- if loop.first %}
						<tr class='interlude win'><td colspan=10>WINNING TEAM</td></tr>
						{%- else %}
						<tr class='interlude lose'><td colspan=10>LOSING TEAM</td></tr>
						{%- endif %}
						{%- for player in team.list %}
						<tr class='player{% if player.blue_team %} team_blue{% else %} team_purple{% endif %}{% if player.won %} won{% else %} lose{% endif %}{% if player.afk or player.leaver %} leaver {% endif %}'>
							<td class='champion'>{{sprites.champion(player.champion_id)}}<small>{{player.champion_level}}</small></td>
							<td><a href='{{player.summoner.get_absolute_url()}}'{% if metadata.ranked %} title='Rating: {{player.get_tier_display()}} {{player.get_division_display()}}'{% endif %}>{{player.summoner.name}}</a></td>
							<td>{{player.kills}}/{{player.deaths}}/{{player.assists}}</td>
							<td>{{player.gold|to_k_format}}</td>
							<td>{{player.minion_kills+player.neutral_minions_killed}}</td>
							<td>{{player.damage_dealt|to_k_format}}</td>
							<td>{{player.damage_taken|to_k_format}}</td>
							<td>{{sprites.summoner(player.summoner_spell1, style='margin-right:4px;')}}{{sprites.summoner(player.summoner_spell2)}}</td>
							<td>
								{%- for item in player.get_items %}
								{{sprites.item(item)}}
								{%- endfor %}
							</td>
							<td><span class='glyphicon glyphicon-chevron-down player_expand' data-player='{{player.pk}}'></span></td>
						</tr>
						{%- endfor %}
						{%- endfor %}
					</table>
				</div>
				<div class='col-md-12'>
					<div class='row'>
						<div class='col-md-3 no-margin'>
							<div class='text-center'><strong>Damage Dealt</strong></div>
							<div id='damage-dealt-graph' style='height:220px;'></div>
						</div>
						<div class='col-md-3 no-margin'>
							<div class='text-center'><strong>Damage Taken</strong></div>
							<div id='damage-taken-graph' style='height:220px;'></div>
						</div>
						<div class='col-md-3 no-margin'>
							<div class='text-center'><strong>GPM</strong></div>
							<div id='gpm-graph' style='height:220px;'></div>
						</div>
						<div class='col-md-3 no-margin'>
							<div class='text-center'><strong>Gold</strong></div>
							<div id='gold-graph' style='height:220px;'></div>
						</div>
					</div>
				</div>
				{%- else %}
				{{update_in_queue}}
				{% endif %}
			</div>
{%- endblock %}

lol/templates/view_summoner.html.j2
{% extends 'base.html.j2' %}

{% block title %}{{summoner.name}}{%- endblock %}

{% block extra_css %}
		<link href="{{STATIC_URL}}css/morris.css" rel="stylesheet" type="text/css">
{%- endblock %}

{% block post_scripts %}
		{%- if debug %}
		<script src='{{STATIC_URL}}debug/items.js' type='text/javascript'></script>
		<script src='{{STATIC_URL}}debug/core.js' type='text/javascript'></script>
		<script src='{{STATIC_URL}}debug/graph.js' type='text/javascript'></script>
		<script src='{{STATIC_URL}}debug/player.js' type='text/javascript'></script>
		{%- else %}
		<script src="{{STATIC_URL}}js/main.js" type="text/javascript"></script>
		{%- endif %}
		<script src='{{STATIC_URL}}js/morris.js' type='text/javascript'></script>
		<script type="text/javascript">
			var account_id={{summoner.account_id}};
			var region={{summoner.region}};
			{%- if stats.count>0 %}
			var chart={'chart_options':{'ymin':'auto', 'ymax':'auto', 'smooth':true, 'labels':['League',], 'pointSize':0, 'hideHover':'auto'}, 'data_options':{'y':'date', 'data_parse':'lcs'}};
			var chart_data={{stats.elo_toJSON()|safe}};
			{%- endif %}
		</script>
{%- endblock %}

{% block content %}
			<div class='row'>
				<div class='summoner-header col-md-12' style='background-image:url({{STATIC_URL}}img/champion-backgrounds/{{stats.by_count()|first|first}}.png)'>
					{#- <div class='pull-left sprite sprite-profile-{{summoner.profile_icon}}'></div> #}
					<div class='pull-left'>{{sprites.profile(summoner.profile_icon, size='large')}}</div>
					<div class='info-block pull-right'>
						<div>
							<b>{{summoner.level}}</b>
							<small>LEVEL</small>
						</div>
						<div>
							<b>{{stats.display_count}}</b>
							<small>GAMES</small>
						</div>
					</div>
					<div class='name-block'>
						<b>{{summoner.name}}</b>
						{#- <span id='spectate-info'><a href='{{spectate.url}}'>{{spectate.player_info(summoner.region, summoner.account_id)}}</a></span> #}
					</div>
					<div class='league-block'>
						{%- if rating.tier %}
						<img src='{{STATIC_URL}}img/leagues/{{rating.tier}}-{{rating.division}}.png' title='Division {{rating.division}} {{rating.get_tier_display()}}' alt='League Icon'>
						<b>{{rating.get_division_display()}}</b>
						{%- else %}
						<img src='{{STATIC_URL}}img/leagues/0.png' title='Unranked' alt='League Icon'>
						{%- endif %}
					</div>
					<div class='bottom-right' id='last-updated-block'>
						{%- if not update_in_queue and summoner.time_updated|timediff > 60*30 %}
						<a href='javascript:void(0);' id='force-update'>
							<small id='last-updated'>LAST UPDATED:{% if not update_in_queue %}{{summoner.time_updated|naturaltime|upper}}{% else %}{{update_in_queue}}{% endif %}</small>
						</a>
						{%- else %}
						<small id='last-updated'>LAST UPDATED:{% if not update_in_queue %}{{summoner.time_updated|naturaltime|upper}}{% else %}{{update_in_queue}}{% endif %}</small>
						{%- endif %}
					</div>
					<ul class='mynav mynav-tabs'>
						<li class='active'><a href='{{summoner.get_absolute_url()}}'>OVERVIEW</a></li>
						<li><a href='{{summoner.get_games_url()}}'>GAMES</a></li>
						<li><a href='{{summoner.get_champions_url()}}'>CHAMPIONS</a></li>
					</ul>
				</div>
			</div>
			<div class='row'>
				<div class='col-md-9' id='games'>
					<table class='game-list table table-condensed'>
						<thead>
							<tr>
								<th style='width:40px;'></th>
								<th style='width:50px'>K/D/A</th>
								<th style='width:50px'>CS</th>
								<th style='width:50px'>Gold</th>
								<th style='width:85px;'>Spells</th>
								<th style='width:215px;'>Items</th>
								<th style='width:50px;'>Date</th>
								<th style='width:10px;'></th>
							</tr>
						</thead>
						<tbody>{% for player in games[:10] %}
							<tr class='{% if player.won %}good{% else %}bad{% endif %}'>
								<td class='champion'>{{sprites.champion(player.champion_id)}}<small>{{player.champion_level}}</small></td>
								<td>{{player.kills}}/{{player.deaths}}/{{player.assists}}</td>
								<td>{{player.minion_kills+player.neutral_minions_killed}}</td>
								<td>{{player.gold|to_k_format}}</td>
								<td>{{sprites.summoner(player.summoner_spell1, style='margin-right:4px;')}}{{sprites.summoner(player.summoner_spell2)}}</td>
								<td>
									{%- for item in player.get_items %}
									{{sprites.item(item)}}
									{%- endfor %}
								</td>
								<td>{{player.game.time|date('M d')}}</td>
								<td><a href='{{player.game.get_absolute_url()}}'>&raquo;</a>{% if (player.game.game_mode, player.game.game_map) in GAME_TYPES.RANKED_GAME_TYPES %}<small class='glyphicon glyphicon-ok' title='Ranked'></small>{% endif %}</td>
							</tr>{% endfor %}
						</tbody>
					</table>
				</div>
				<div class='best-stats col-md-3 pull-right'>
					<div class='header'>
						<strong>Best Champions</strong>
					</div>
					{% for champion in stats.best_ratio()[:3] %}<div class='champion'>
						{{sprites.champion(champion.0, size='large')}}
						<div class='vert-bar'>
							<div class='red' style='height:{{champion.1.lost|get_percent(champion.1.count)}};'></div>
							<div class='green' style='height:{{champion.1.won|get_percent(champion.1.count)}};'></div>
						</div>
						<div class='stats pull-right'>
							<small>GAMES:</small><b>{{champion.1.count}}</b><br>
							<small>WINS:</small><b>{{champion.1.won}}</b><br>
							<small>LOSSES:</small><b>{{champion.1.lost}}</b>
						</div>
					</div>{% endfor %}
				</div>
			</div>
			<div class='row'>
				<div class='col-md-12'>
					<div class='row'>
						<div class='col-md-12' id='elo-graph' style='height:340px;width:100%;margin:6px 0 0 0;'></div>
					</div>
				</div>
			</div>
			{{stats.index.friends}}
			{%- if user.is_staff and rating.tier %}
			<div class='row'>
				<div class='col-md-12'>
					<pre>
						Rank:{{rating.rank}}
						Wins:{{rating.wins}}
						Losses:{{rating.losses}}
						Miniseries:{Target:{{rating.miniseries_target}}, Wins:{{rating.miniseries_wins}}, Losses:{{rating.miniseries_losses}}}
					</pre>
				</div>
			</div>
			{%- endif %}
{%- endblock %}